/**
 * =====================================================================
 * Eslint Configuration (Flat)
 * =====================================================================
 * Purpose: Project-wide ESLint configuration for Next.js, TypeScript, and
 *          React. Enforces code quality, accessibility, and consistent styling.
 * Docs:    https://eslint.org/docs/latest/use/configure/configuration-files-new
 * Usage:   npx eslint .
 * =====================================================================
 */

import { createConfig } from '@vijayhardaha/dev-config/eslint/next';

const baseConfig = createConfig();

// supabase/.temp is a gitignored scratch dir generated by the Supabase CLI;
// exclude it so `eslint .` does not fail on generated files.
const config = Array.isArray(baseConfig) ? baseConfig : [baseConfig];

config.push({ ignores: ['supabase/.temp/**', '**/supabase/.temp/**'] });

export default config;
