-- Seed default categories
INSERT INTO public.categories (id, value, name, color, description) VALUES
  (gen_random_uuid(), 'marches', 'Marches', 'yellow', 'Organised marches and processions'),
  (gen_random_uuid(), 'rallies', 'Rallies', 'black', 'Public rallies and gatherings'),
  (gen_random_uuid(), 'candlelight', 'Candlelight', 'blue', 'Candlelight vigils and peaceful night protests'),
  (gen_random_uuid(), 'art', 'Art', 'red', 'Protest art, murals, and creative expression'),
  (gen_random_uuid(), 'youth', 'Youth', 'green', 'Student and youth-led actions'),
  (gen_random_uuid(), 'press', 'Press', 'white', 'Press conferences and media interactions')
ON CONFLICT (value) DO NOTHING;
-- Seed default locations

INSERT INTO public.locations (id, value, name) VALUES
  (gen_random_uuid(), 'andhra-pradesh', 'Andhra Pradesh'),
  (gen_random_uuid(), 'arunachal-pradesh', 'Arunachal Pradesh'),
  (gen_random_uuid(), 'assam', 'Assam'),
  (gen_random_uuid(), 'bihar', 'Bihar'),
  (gen_random_uuid(), 'chhattisgarh', 'Chhattisgarh'),
  (gen_random_uuid(), 'goa', 'Goa'),
  (gen_random_uuid(), 'gujarat', 'Gujarat'),
  (gen_random_uuid(), 'haryana', 'Haryana'),
  (gen_random_uuid(), 'himachal-pradesh', 'Himachal Pradesh'),
  (gen_random_uuid(), 'jharkhand', 'Jharkhand'),
  (gen_random_uuid(), 'karnataka', 'Karnataka'),
  (gen_random_uuid(), 'kerala', 'Kerala'),
  (gen_random_uuid(), 'madhya-pradesh', 'Madhya Pradesh'),
  (gen_random_uuid(), 'maharashtra', 'Maharashtra'),
  (gen_random_uuid(), 'manipur', 'Manipur'),
  (gen_random_uuid(), 'meghalaya', 'Meghalaya'),
  (gen_random_uuid(), 'mizoram', 'Mizoram'),
  (gen_random_uuid(), 'nagaland', 'Nagaland'),
  (gen_random_uuid(), 'odisha', 'Odisha'),
  (gen_random_uuid(), 'punjab', 'Punjab'),
  (gen_random_uuid(), 'rajasthan', 'Rajasthan'),
  (gen_random_uuid(), 'sikkim', 'Sikkim'),
  (gen_random_uuid(), 'tamil-nadu', 'Tamil Nadu'),
  (gen_random_uuid(), 'telangana', 'Telangana'),
  (gen_random_uuid(), 'tripura', 'Tripura'),
  (gen_random_uuid(), 'uttar-pradesh', 'Uttar Pradesh'),
  (gen_random_uuid(), 'uttarakhand', 'Uttarakhand'),
  (gen_random_uuid(), 'west-bengal', 'West Bengal'),
  (gen_random_uuid(), 'delhi', 'Delhi'),
  (gen_random_uuid(), 'chandigarh', 'Chandigarh'),
  (gen_random_uuid(), 'andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'),
  (gen_random_uuid(), 'dadra-and-nagar-haveli-and-daman-and-diu', 'Dadra and Nagar Haveli and Daman and Diu'),
  (gen_random_uuid(), 'jammu-and-kashmir', 'Jammu and Kashmir'),
  (gen_random_uuid(), 'ladakh', 'Ladakh'),
  (gen_random_uuid(), 'lakshadweep', 'Lakshadweep'),
  (gen_random_uuid(), 'puducherry', 'Puducherry'),
  (gen_random_uuid(), 'foreign', 'Foreign (Outside India)')
ON CONFLICT (value) DO NOTHING;
