-- New categories from demo.md with full SEO metadata
INSERT INTO public.categories (value, name, color, description, seo_title, seo_description) VALUES
  ('protest-marches', 'Protest Marches', 'saffron',
   'Explore publicly shared videos of protest marches across India, featuring peaceful rallies, processions, public gatherings, patriotic songs, and community participation.',
   'Student Protest March Videos',
   'Explore publicly shared videos of protest marches across India, featuring peaceful rallies, processions, public gatherings, patriotic songs, and community participation.'),
  ('police-conduct', 'Police Conduct', 'navy',
   'Browse videos documenting police presence, crowd management, barricading, detentions, and alleged use of force during student protests across India.',
   'Police Conduct During Student Protests',
   'Browse videos documenting police presence, crowd management, barricading, detentions, and alleged use of force during student protests across India.'),
  ('night-updates', 'Night Updates', 'indigo',
   'Watch videos recorded during evening and overnight protests, including candlelight vigils, volunteer efforts, speeches, and updates from protest sites.',
   'Student Protest Night Updates',
   'Watch videos recorded during evening and overnight protests, including candlelight vigils, volunteer efforts, speeches, and updates from protest sites.'),
  ('gen-z-movement', 'Gen Z Movement', 'green',
   'Discover videos highlighting the leadership, creativity, participation, and voices of Gen Z students during peaceful protests and public movements.',
   'Gen Z Student Movement Videos',
   'Discover videos highlighting the leadership, creativity, participation, and voices of Gen Z students during peaceful protests and public movements.'),
  ('official-statements', 'Official Statements', 'white',
   'Explore official announcements, press briefings, speeches, campaign updates, and public statements shared by protest organizers and representatives.',
   'Official Student Protest Statements',
   'Explore official announcements, press briefings, speeches, campaign updates, and public statements shared by protest organizers and representatives.'),
  ('public-figures-creators', 'Public Figures & Creators', 'yellow',
   'Watch videos shared by influencers, journalists, actors, educators, activists, and other public figures documenting or supporting student protests.',
   'Public Figures at Student Protests',
   'Watch videos shared by influencers, journalists, actors, educators, activists, and other public figures documenting or supporting student protests.'),
  ('news-coverage', 'News Coverage', 'blue',
   'Browse television reports, digital news clips, interviews, debates, and media coverage documenting student protests and related developments.',
   'Student Protest News Coverage',
   'Browse television reports, digital news clips, interviews, debates, and media coverage documenting student protests and related developments.'),
  ('protest-vlogs', 'Protest Vlogs', 'purple',
   'Explore personal vlog style videos documenting journeys, behind the scenes moments, daily experiences, and firsthand accounts from protest participants.',
   'Student Protest Vlogs',
   'Explore personal vlog style videos documenting journeys, behind the scenes moments, daily experiences, and firsthand accounts from protest participants.'),
  ('acts-of-kindness', 'Acts of Kindness', 'pink',
   'Discover inspiring moments of compassion, solidarity, volunteer support, food distribution, medical assistance, and kindness shared during protests.',
   'Kindness During Student Protests',
   'Discover inspiring moments of compassion, solidarity, volunteer support, food distribution, medical assistance, and kindness shared during protests.'),
  ('women-leading', 'Women Leading the Movement', 'orange',
   'Explore videos highlighting women leading marches, organizing events, delivering speeches, coordinating volunteers, and inspiring peaceful public participation.',
   'Women Leading Student Protests',
   'Explore videos highlighting women leading marches, organizing events, delivering speeches, coordinating volunteers, and inspiring peaceful public participation.'),
  ('solidarity-protection', 'Solidarity & Protection', 'teal',
   'Watch videos showing protesters protecting one another, supporting vulnerable participants, forming human chains, and demonstrating unity during protests.',
   'Solidarity During Student Protests',
   'Watch videos showing protesters protecting one another, supporting vulnerable participants, forming human chains, and demonstrating unity during protests.'),
  ('senior-citizens-voices', 'Senior Citizens'' Voices', 'amber',
   'Discover speeches, interviews, and heartfelt messages from senior citizens sharing support, advice, and perspectives on student movements across India.',
   'Senior Citizens Supporting Student Protests',
   'Discover speeches, interviews, and heartfelt messages from senior citizens sharing support, advice, and perspectives on student movements across India.'),
  ('childrens-voices', 'Children''s Voices', 'lime',
   'Browse publicly shared videos featuring children expressing messages of hope, participation, awareness, and support alongside peaceful public demonstrations.',
   'Children''s Voices During Student Protests',
   'Browse publicly shared videos featuring children expressing messages of hope, participation, awareness, and support alongside peaceful public demonstrations.'),
  ('human-rights', 'Human Rights', 'red',
   'Explore videos documenting alleged human rights concerns, civil liberties issues, public accountability, and reported incidents during student protests.',
   'Human Rights During Student Protests',
   'Explore videos documenting alleged human rights concerns, civil liberties issues, public accountability, and reported incidents during student protests.'),
  ('celebrations-cultural', 'Celebrations & Cultural Events', 'rose',
   'Discover patriotic songs, cultural performances, celebrations, street art, poetry, music, and creative expressions shared during student protests.',
   'Cultural Events During Student Protests',
   'Discover patriotic songs, cultural performances, celebrations, street art, poetry, music, and creative expressions shared during student protests.'),
  ('counter-protests', 'Counter Protests & Public Reactions', 'cyan',
   'Explore videos documenting counter demonstrations, differing viewpoints, public reactions, debates, and discussions surrounding student protests.',
   'Counter Protest Videos',
   'Explore videos documenting counter demonstrations, differing viewpoints, public reactions, debates, and discussions surrounding student protests.'),
  ('media-analysis', 'Media Analysis', 'slate',
   'Browse videos discussing, comparing, or analyzing media coverage, reporting styles, public criticism, and journalism related to student protests.',
   'Student Protest Media Analysis',
   'Browse videos discussing, comparing, or analyzing media coverage, reporting styles, public criticism, and journalism related to student protests.')
ON CONFLICT (value) DO UPDATE SET
  name = EXCLUDED.name,
  color = EXCLUDED.color,
  description = EXCLUDED.description,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description;
